services:
  # Next.js frontend application
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - MONGODB_URI=mongodb://mongo:27017/subscription-tracker
      - NEXTAUTH_SECRET=nnpy
      - NEXTAUTH_URL=http://localhost:3000
    depends_on:
      - mongo
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    ports:
      - 27017:27017

volumes:
  mongo-data:
