services:
  # Next.js frontend application
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - .env.local
    depends_on:
      - mongo
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    ports:
      - 27018:27017

volumes:
  mongo-data:
